# NumPy Basics

This section introduces some basics of NumPy, a linear algebra and matrix manipulation library.

We begin by importing NumPy, which by convention is imported as `np` to save typing.

In [1]:
import numpy as np

## 1-Dimensional Data Structures

First, we will look at 1-dimensional data structures.

In [2]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This represents a 1-dimensional NumPy array (vector) of length 10.

You can access elements using 0-based indexing:

In [3]:
v[3]

3

Accessing a range of values can be done using the `:` operator:

In [4]:
v[0:3]

array([0, 1, 2])

For brevity, you can omit the first index. Omitting the second index means until the last element:

In [5]:
v[:3]

array([0, 1, 2])

Using negative indexing selects elements relative to the end:

In [6]:
v[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
v[-3:]

array([7, 8, 9])

Leaving indexes out entirely selects the whole array:

In [8]:
v[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Array broadcasting applies operations to all elements without loops:

In [9]:
v += 1
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D Arrays (Matrices)

NumPy can handle multidimensional matrices. Indexing is done by rows and columns using a comma.

In [10]:
m = np.arange(9).reshape(3, 3)

In [11]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Indexing 2D Arrays

In [12]:
m[0]

array([0, 1, 2])

In [13]:
m[0, 1]

1

In [14]:
m[:, 0]

array([0, 3, 6])

### Advanced Slicing

In [15]:
m[:, ::2]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [16]:
m[::2, ::2]

array([[0, 2],
       [6, 8]])

## Element-wise Operations

In [17]:
m**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [18]:
m + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Operations Between 2D and 1D Arrays

In [19]:
n = np.array([1, 2, 3])
n

array([1, 2, 3])

In [20]:
m + n

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [21]:
m * n

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])